# Site settings
title: Introduction to Classical Archaeology, S'14
email: nsmith@holycross.edu
description: > # this means to ignore newlines until "baseurl:"
  Course discussion blog for Introduction to Classical Archaeology,
  Classics 160, College of the Holy Cross, spring semester, 2014.
baseurl: "/ica-s14"
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
